// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace RemittanceAdvice
{
	public partial class PaymentsViewController : UIViewController
	{
		public PaymentsViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
